### ISSUE TITLE
face/object recognition

### ISSUE THREAD

**Issue by faspina** [dlandon/zoneminder#21]
I am following your progress on this. Anxiously await the full support of zmeventnotification object recognition. Good luck

**Comment by dlandon** [comment]
I have implemented the file structure and location of files and scripts to support the hook feature from the zmeventnotification installation guide.  I don't intend to totally implement the hook feature in the docker, I am only setting things up for the user to do their own work.    The files are placed in the /config/hook folder in the proper place and the docker places them in the docker image in the correct places when it starts.  I am waiting for some feedback from someone who is currently using the hook feature.

**Comment by faspina** [comment]
Has the readme been followed here
https://github.com/pliablepixels/zmeventnotification

Or is that whereI need to start in the container

**Comment by dlandon** [comment]
No.  This is the readme for the hook processing.
https://github.com/pliablepixels/zmeventnotification/tree/master/hook

I followed that.

Here is a description of how the hook processing is set up in the docker image.
https://forums.unraid.net/topic/56632-support-dlandon-zoneminder-132/

You don't want to do anything directly in the docker image because it is not persistent if the docker is updated or reloaded.  The above write up describes how you set up your files and run a userscript.sh to install all the drivers needed.  Be sure to read about how to set the environment variable to enable the user script.  The docker will set up everything from your /config/hook folder.

**Comment by faspina** [comment]
I have userscript.sh in my folder 
I did a chmod +x userscript.sh on the host.

even though it says users script found in the log I don't think the userscript ever runs. 

When I go to the docker's console, PIP is not installed . I can install it manually with apt-get -y install python-pip

I can execute it with sh userscript.sh on the host it runs but does not work I think I am in the wrong directory.
